# Generated by Django 3.0.5 on 2020-05-11 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_auto_20200509_1546'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('creator_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('full_url', models.CharField(max_length=450)),
                ('short_code', models.CharField(max_length=30, unique=True)),
                ('do_collect_meta', models.BooleanField(default=True)),
                ('alias', models.BooleanField(default=False)),
                ('view_data_code', models.CharField(default=None, max_length=31, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.UserAPIKey')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_referer', models.CharField(default=None, max_length=999, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(max_length=999)),
                ('IP', models.GenericIPAddressField(default='127.0.0.1')),
                ('shorturl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlshortner.ShortUrl')),
            ],
        ),
    ]
