# Generated by Django 3.0.5 on 2020-04-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaOfFollowedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('time_clicked', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorUser',
            fields=[
                ('metaoffolloweduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='urlshortner.MetaOfFollowedUser')),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
            bases=('urlshortner.metaoffolloweduser',),
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_collect_meta', models.BooleanField(default=True)),
                ('short_code', models.CharField(max_length=18)),
                ('full_url', models.URLField(max_length=300)),
                ('meta', models.ManyToManyField(to='urlshortner.MetaOfFollowedUser')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_created_url', to='urlshortner.AuthorUser')),
            ],
        ),
    ]
