# Generated by Django 3.0.5 on 2020-04-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='meta',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='meta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='urlshortner.MetaOfFollowedUser'),
        ),
    ]
