# Generated by Django 3.0.5 on 2020-04-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_auto_20200408_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='who_created_url', to='urlshortner.AuthorUser'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='meta',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='urlshortner.MetaOfFollowedUser'),
        ),
    ]
