# Generated by Django 3.0.5 on 2020-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_auto_20200408_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=18)),
                ('time_clicked', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(max_length=300)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='meta',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='creator_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='times_clicked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AuthorUser',
        ),
        migrations.DeleteModel(
            name='MetaOfFollowedUser',
        ),
    ]
