# Generated by Django 3.0.5 on 2020-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0004_auto_20200408_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='time_clicked',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='short_code',
        ),
        migrations.AddField(
            model_name='visit',
            name='address',
            field=models.URLField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
