# Generated by Django 3.0.5 on 2020-04-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0005_auto_20200408_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
