# Generated by Django 3.0.5 on 2020-04-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0007_auto_20200409_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='shorturl',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='urlshortner.ShortUrl'),
            preserve_default=False,
        ),
    ]
