# Generated by Django 3.0.5 on 2020-04-10 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlshortner', '0009_remove_visit_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='ip',
            new_name='IP',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
