# Generated by Django 3.0.5 on 2020-04-10 00:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlshortner', '0010_auto_20200410_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
