# Generated by Django 3.0.5 on 2020-04-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0013_auto_20200410_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='alias',
            field=models.BooleanField(default=False),
        ),
    ]
